### ISSUE TITLE
Extremely slow code in debug

### ISSUE THREAD

**Issue by AndreyOrb** [Urban82/Aes256#7]
Current implementation uses 
`typedef std::vector<unsigned char> ByteArray;`
to work with chars arrays (keys, plain, salt, etc.).

Running encrypt/decrypt on big files is x100 times slower in debug (compared to release) because of iterators.

**Comment by Urban82** [comment]
Debug version is slower because of `-O0` optimization (instead of `-O3` on Release version) and not because of iterators. But `-O0` is needed if you have to run through gdb.

If you need to compile Debug but you don't need gdb, you can add optimization flag (at least `-O2`) to variable `compiler_common_flags` on `CMakeLists.txt`.
